### ISSUE TITLE
About InlineContent in TextFlow

### ISSUE THREAD

**Issue by choristery** [oleksandrbalan/textflow#2]
Hi. I'm trying TextFlow.

If there is `inlineContent` in `AnnotatedString` it cannot be used normally. This kind of scene is more common in reading, for example: 

[author's photo] a paragraph about the author [img annotation] other content.

When using `TextFlow` to provide a text wrapping effect for [author's photo], the image annotation cannot be displayed using `inlineContent`.

Have a better suggestion?

**Comment by oleksandrbalan** [comment]
Hey 👋 

Yea, I am aware that TextFlow does not work correctly with inlined content 😢 

You could try https://github.com/romainguy/combo-breaker, which should support much more complex use-cases 👀

**Comment by choristery** [comment]
Unfortunately, `[combo-breaker](https://github.com/romainguy/combo-breaker)` also does not support inlined content.
