### ISSUE TITLE
Multiple ellipses when overflow set to TextOverflow.Ellipsis

### ISSUE THREAD

**Issue by ryandt** [oleksandrbalan/textflow#3]
👋🏼 Hey there. When setting `overflow` to `TextOverflow.Ellipsis`, the text renders two ellipses instead of the expected one ellipsis at the end of the last line.

![image](https://github.com/oleksandrbalan/textflow/assets/4073952/86923d20-5954-452b-bf73-63604c66cec6)

**Comment by oleksandrbalan** [comment]
Hi 👋 

Thx for your report, I fixed an issue in #4 and now releasing a new 1.1.1 version with a fix 👌

**Comment by ryandt** [comment]
The update works like a charm. Thanks Alex!
