### ISSUE TITLE
Changing the color of a TextFlow via State doesn't work.

### ISSUE THREAD

**Issue by hbdeveloppeur** [oleksandrbalan/textflow#7]
Thanks for your library!

It seems like I can only set one color, changing the color of a TextFlow via a user action doesn't work

**Comment by oleksandrbalan** [comment]
Thanks for using a library 🤗 

That was an interesting bug 😄 
Looks like `TextMeasurer` does not get invalidated when color or text decoration is changed, it is now fixed in #8.
I will release a new version soon 👌

**Comment by oleksandrbalan** [comment]
Should be fixed in 1.1.2 👌 
Could you please confirm that it works for you?

**Comment by hbdeveloppeur** [comment]
This working like a charm, thank you for your work
